### ISSUE TITLE
Exception in backend module

### ISSUE THREAD

**Issue by wowawebdesign** [nimius/tx_workshops#2]
In the backend module I got an exception. It's independant from the PHP version.
(TYPO3 7.6.9, PHP 7.0.0 and 5.6.10)

![workshops-be-module](https://cloud.githubusercontent.com/assets/343511/16225903/40ff3b84-37a9-11e6-9a3e-38a3c3a6f3a0.png)

**Comment by pduersteler** [comment]
Thanks for testing. This is already fixed in the development branch and will be fixed with publishing v1.1.0.
